<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MesinSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $timestamp = Carbon::now()->toDateTimeString();
        $mesin = array(
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-43', 'keterangan' => 'RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-42', 'keterangan' => 'RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-05', 'keterangan' => 'RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-06', 'keterangan' => 'RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-07', 'keterangan' => 'RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-08', 'keterangan' => 'RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-09', 'keterangan' => 'RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-10', 'keterangan' => 'RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-11', 'keterangan' => 'RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-12', 'keterangan' => 'RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-14', 'keterangan' => 'RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-15', 'keterangan' => 'RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-16', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-17', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-18', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-19', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-20', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-21', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-22', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-23', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-24', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-25', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 2000 CC', 'no_mesin' => '02-IMD-32', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 1000 CC', 'no_mesin' => '02-IMD-31', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ KUEMIN 200 TON', 'no_mesin' => '01-IMD-07', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ REP TUNGYU 2000 CC', 'no_mesin' => '02-IMD-62', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 2000 CC', 'no_mesin' => '02-IMD-53', 'keterangan' => 'RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 1000 CC', 'no_mesin' => '02-IMD-43', 'keterangan' => 'RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'JIN JINGDAY 1000 CC', 'no_mesin' => '02-IMD-27', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 1000 CC', 'no_mesin' => '02-IMD-26', 'keterangan' => 'RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 1000 CC', 'no_mesin' => '02-IMD-25', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 1000 CC', 'no_mesin' => '02-IMD-24', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 2000 CC', 'no_mesin' => '02-IMD-34', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 2000 CC', 'no_mesin' => '02-IMD-33', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 2000 CC', 'no_mesin' => '02-IMD-22', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 2000 CC', 'no_mesin' => '02-IMD-23', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ REP TUNGYU 2000 CC', 'no_mesin' => '02-IMD-44', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ REP TUNGYU 2000 CC', 'no_mesin' => '02-IMD-45', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ REP TUNGYU 2000 CC', 'no_mesin' => '02-IMD-46', 'keterangan' => 'RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ REP TUNGYU 2000 CC', 'no_mesin' => '02-IMD-47', 'keterangan' => 'RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ REP TUNGYU 2000 CC', 'no_mesin' => '02-IMD-48', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ REP TUNGYU 2000 CC', 'no_mesin' => '02-IMD-49', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ REP TUNGYU 2000 CC', 'no_mesin' => '02-IMD-50', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ REP TUNGYU 2000 CC', 'no_mesin' => '02-IMD-54', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ REP TUNGYU 2000 CC', 'no_mesin' => '02-IMD-55', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ REP TUNGYU 2000 CC', 'no_mesin' => '02-IMD-58', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ REP TUNGYU 1000 CC', 'no_mesin' => '02-IMD-57', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ REP TUNGYU 1000 CC', 'no_mesin' => '02-IMD-56', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ REP TUNGYU 1000 CC', 'no_mesin' => '02-IMD-59', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ REP TUNGYU 1000 CC', 'no_mesin' => '02-IMD-60', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ REP TUNGYU 1000 CC', 'no_mesin' => '02-IMD-61', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM PANSTONE', 'no_mesin' => '02-MVC-51', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM PANSTONE', 'no_mesin' => '02-MVC-50', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-01', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-02', 'keterangan' => 'RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-03', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-04', 'keterangan' => 'RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM PRESS PANSTONE', 'no_mesin' => '02-MVC-52', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM PRESS PANSTONE', 'no_mesin' => '02-MVC-53', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM PRESS PANSTONE', 'no_mesin' => '02-MVC-54', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM PRESS PANSTONE', 'no_mesin' => '02-MVC-55', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'MOULD 200 TON', 'no_mesin' => '01-KOK-24', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'MOULD 200 TON', 'no_mesin' => '01-KOK-25', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'MEISHO 150 TON', 'no_mesin' => '01-MEI-32', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'MEISHO 150 TON', 'no_mesin' => '01-MEI-33', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-41', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-40', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-39', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VACUM JINGDAY 250 TON', 'no_mesin' => '02-MVC-38', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 1000 CC', 'no_mesin' => '02-IMD-30', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 1000 CC', 'no_mesin' => '02-IMD-29', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 1000 CC', 'no_mesin' => '02-IMD-28', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 1000 CC', 'no_mesin' => '02-IMD-20', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 1000 CC', 'no_mesin' => '02-IMD-19', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 1000 CC', 'no_mesin' => '02-IMD-18', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 1000 CC', 'no_mesin' => '02-IMD-17', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 1000 CC', 'no_mesin' => '02-IMD-16', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 1000 CC', 'no_mesin' => '02-IMD-15', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 1000 CC', 'no_mesin' => '02-IMD-12', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 1000 CC', 'no_mesin' => '02-IMD-11', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 1000 CC', 'no_mesin' => '02-IMD-10', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 1000 CC', 'no_mesin' => '02-IMD-09', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 1000 CC', 'no_mesin' => '02-IMD-07', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 1000 CC', 'no_mesin' => '02-IMD-03', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 1000 CC', 'no_mesin' => '02-IMD-06', 'keterangan' => 'RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 1000 CC', 'no_mesin' => '02-IMD-05', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ KUEMIN 1000 CC', 'no_mesin' => '02-IMD-01', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ KUEMIN 1000 CC', 'no_mesin' => '02-IMD-02', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ KUEMIN 1000 CC', 'no_mesin' => '02-IMD-04', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ REP TUNGYU 1000 CC', 'no_mesin' => '02-IMD-63', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ REP TUNGYU 1000 CC', 'no_mesin' => '02-IMD-64', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ REP TUNGYU 1000 CC', 'no_mesin' => '02-IMD-51', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ REP TUNGYU 1000 CC', 'no_mesin' => '02-IMD-52', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ MATSUDA 2000 CC', 'no_mesin' => '02-IMD-09', 'keterangan' => 'RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ SANYU 2000 CC', 'no_mesin' => '01-SAN-02', 'keterangan' => 'RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ SANYU 2000 CC', 'no_mesin' => '01-SAN-01', 'keterangan' => 'RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VAC JINGDAY 300 CC', 'no_mesin' => '02-MVC-33', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VAC JINGDAY 300 CC', 'no_mesin' => '02-MVC-34', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VAC JINGDAY 300 CC', 'no_mesin' => '02-MVC-35', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VAC JINGDAY 300 CC', 'no_mesin' => '02-MVC-28', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VAC JINGDAY 300 CC', 'no_mesin' => '02-MVC-26', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VAC JINGDAY 300 CC', 'no_mesin' => '02-MVC-36', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 1000 CC', 'no_mesin' => '02-IMD-36', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VAC JINGDAY 300 CC', 'no_mesin' => '02-MVC-37', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VAC JINGDAY 300 CC', 'no_mesin' => '02-MVC-27', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 1000 CC', 'no_mesin' => '02-IMD-37', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 1000 CC', 'no_mesin' => '02-IMD-42', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VAC JINGDAY 300 CC', 'no_mesin' => '02-MVC-29', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VAC JINGDAY 300 CC', 'no_mesin' => '02-MVC-31', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VAC JINGDAY 300 CC', 'no_mesin' => '02-MVC-32', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'VAC JINGDAY 300 CC', 'no_mesin' => '02-MVC-30', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
            array('name_mesin' => 'INJ JINGDAY 1000 CC', 'no_mesin' => '02-IMD-35', 'keterangan' => 'TIDAK RUSAK', 'created_at' => $timestamp, 'updated_at' => $timestamp),
        );
        DB::table('mesins')->insert($mesin);
    }
}
